### ISSUE TITLE
Configuração em um YAML

### ISSUE THREAD

**Issue by danieldocki** [eventick/pagseguro-transparente#15]
Pessoal,

Concordam com a configuração em um yaml?

pagseguro.yml
```
development:
  adapter_javascript_url: "https://stc.sandbox.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js"
  email: "exemplo@pagseguro.com.br"
  token: "token válido"
  api_url: "https://ws.sandbox.pagseguro.uol.com.br/"

production:
  adapter_javascript_url: "https://stc.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js"
  email: "exemplo@pagseguro.com.br"
  token: "token válido"
  api_url: "https://ws.pagseguro.uol.com.br/"
```
